### ISSUE TITLE
SponsorBlock's API Integration

### ISSUE THREAD

**Issue by pgamerx** [pgamerx/yt-dislikes-viewer#10]
Hello everyone,
As mentioned in #6, we need to think of another way to keep our extension working. I came across this issue in [SponsorBlock repo.](https://github.com/ajayyy/SponsorBlock/issues/1039)

I had conversations with a user, and, ajayyy himself. I gave some stupid idea which of course got rejected. But that's not the point. Ajay stated in [This comment](https://github.com/ajayyy/SponsorBlock/issues/1039#issuecomment-971163876) that the backend for this custom rating system's API is ready. We can (should in fact) integrate this API with our system so that if the dislike count for a certain video is not saved in our database, it shows the dislike/like count provided by the SponsorBlock API.

We will also have to add an event listener to know when a user clicked the like button/dislike button on a video and send the same data to the API. This shouldn't be a difficult task but due to my final exams, I have little to no time to work on this so that's why I need your guy's support

**Comment by pgamerx** [comment]
This should be worked on only in [`dev` branch/tree](https://github.com/pgamerx/yt-dislikes-viewer/tree/dev)

**Comment by contourintegrals** [comment]
[retracted]

Edit: Crap, I misunderstood the situation.

**Comment by pgamerx** [comment]
> [retracted]
> 
> Edit: Crap, I misunderstood the situation.

haha
