### ISSUE TITLE
How Do I Get it to Work on Firefox?

### ISSUE THREAD

**Issue by Grip555** [pgamerx/yt-dislikes-viewer#11]
I installed the extension and got Youtube API, but it won't work at all. Also the discord server just links to the donations in the extension itself.

**Comment by pgamerx** [comment]
Hi there, the discord server is available at https://u.pgamerx.com/discord.

I just tried installing the extension at my end and it's working, are you sure you are not installing it from your own and are installing from the Mozilla addon page?

**Comment by pgamerx** [comment]
@Grip555 I am sorry, there was an issue
Try installing the latest version!
