### ISSUE TITLE
Float values for small numbers

### ISSUE THREAD

**Issue by qo4on** [pgamerx/yt-dislikes-viewer#12]
It shows float for small numbers `10.0` instead of `10`.

**Comment by pgamerx** [comment]
Yes, for some reason if I try to .innerhtml an integer, it shows it two times. Like 25 becomes 2525 and 10 becomes 1010

**Comment by thereaper90917** [comment]
should be fixed with this PR https://github.com/pgamerx/yt-dislikes-viewer/pull/14

**Comment by pgamerx** [comment]
Fixed in #14 pog
