### ISSUE TITLE
Unable to get working with Brave

### ISSUE THREAD

**Issue by Diabman** [pgamerx/yt-dislikes-viewer#15]
Version of Brave is: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
Version of the Chromium Build is 1.2 as of this writing. I'm not quite sure what I'm doing wrong. When I go into the extension and load it, it shows up properly but when I go and check a YT video, no dislikes are showing. I go to check the extension and I see this: 
![image](https://user-images.githubusercontent.com/43334755/142572004-2eee92fa-3aad-4d15-a47c-574edf775d2f.png)

I don't see an option to give my Data API Key, either. Any help?

**Comment by pgamerx** [comment]
Hi there, I am checking it on brave and v1.0.2 works for me

**Comment by pgamerx** [comment]
Wait @Diabman, what happens when you click the ICON of extension?

**Comment by pgamerx** [comment]
you don't get something like this?

![Screenshot 2021-11-19 at 11 52 31 AM](https://user-images.githubusercontent.com/71639879/142575148-fed09337-d84c-4a7e-8d74-72585cd7c6fc.png)

**Comment by Diabman** [comment]
I see I had to pin it, trying to mess with it in the extensions menu didn't get me that. I got it working now, thanks for the help. Much appreciated!
