### ISSUE TITLE
Does it show the correct dislike values?

### ISSUE THREAD

**Issue by qo4on** [pgamerx/yt-dislikes-viewer#17]
As far as I can see, your [run()](https://github.com/pgamerx/yt-dislikes-viewer/blob/chromium/script.js#L31) uses the old dislike value from your server, if it exists there. Thus, the user sees this old dislike value in this case. Also, I have not found where you update the existing values in the database.
Disabling the dislikes will greatly reduce the number of people who want to put them up. So, it makes no sense to collect dislikes. If Google does not allow to get the dislikes through their api maybe a better substitute would be `likes count/views count`?

**Comment by pgamerx** [comment]
Hi there, the method you are stating isn't reliable for controversial videos to say the least

**Comment by qo4on** [comment]
Of course it's not perfect. But it's the best we can do in the absence of dislikes.

**Comment by pgamerx** [comment]
> Of course it's not perfect. But it's the best we can do in the absence of dislikes.

I am going to integrate Sponsorblock as I mentioned in #10.
Till that time I have my own API that archives all the dislikes count and fetch them everyday (10k daily).
