### ISSUE TITLE
Now make this, but for safari

### ISSUE THREAD

**Issue by ImNimboss** [pgamerx/yt-dislikes-viewer#2]
Yes

**Comment by pgamerx** [comment]
Maybe in future

**Comment by ImNimboss** [comment]
*sad safari noises*

**Comment by ellieeet123** [comment]
Just install chrome on whatever device you have.

**Comment by SIGSTACKFAULT** [comment]
also, Firefox.

**Comment by ImNimboss** [comment]
@ellieeet123 me and many other people prefer to not use chrome because of its obsessive amount of trackers and data collection, besides I have safari pre-installed on my Mac already
Safari's just as good, if not better
Also it's far too heavy and [takes too much processing power](https://chromeisbad.com)

**Comment by ellieeet123** [comment]
Yeah that makes sense. Sorry if my comment sounded mean.

**Comment by ImNimboss** [comment]
No problem, more people need to know about the liabilities of modern day chrome :)

**Comment by pgamerx** [comment]
@SIGSTACKFAULT FireFox version is ready, it just needs approval of Mozilla

**Comment by pgamerx** [comment]
Firefox version has been approved, google Chrome store version is under review. 

https://addons.mozilla.org/addon/yt-dislikes-viewer/.

**Comment by pgamerx** [comment]
Safari too much work for me because my exams are there from 20th.

**Comment by ImNimboss** [comment]
Rip

**Comment by hisRoyalty** [comment]
I feel safari extensions is way too much work and far from being developed.

However, making a safari extension should be definitely considered in the future.

**Comment by ImNimboss** [comment]
Agreed

**Comment by pgamerx** [comment]
I will not, it costs 99$

**Comment by ImNimboss** [comment]
wtf, pain
