### ISSUE TITLE
This system can easily be abused

### ISSUE THREAD

**Issue by null8626** [pgamerx/yt-dislikes-viewer#27]
Say, i send a request to a URI, like
`https://yt-dislikes-viewer-api.websitedesigne1.repl.co/data/put?video_id=YbJOTdZBX1g&dislike_count=9999999999999999`, the database would blindingly allow the request and saves the update to the database.

Thus, requesting to the `https://yt-dislikes-viewer-api.websitedesigne1.repl.co/data/get?video_id=YbJOTdZBX1g` would output `[ "9999999999999999" ]`, which would obviously be a huge problem, wouldn't it?

**Comment by pgamerx** [comment]
Yes I had figured it out yesterday, from tomorrow this is changing as /data/put will fetch data itself using YouTube's API and save it in the database.

**Comment by null8626** [comment]
This would still not work, since as you've stated in the readme:
> Hey there, I have just checked the Youtube's official change-logs and it seems that they will stop providing dislikes in the youtube Data API.

**Comment by thereaper90917** [comment]
currently there's a few ideas how to approach the extension once YT stops supplying one. feel free to come join the discord and discuss :D any input and help is appreciated thanks for taking the time to point this out as well

**Comment by pgamerx** [comment]
> This would still not work, since as you've stated in the readme:
> > Hey there, I have just checked the Youtube's official change-logs and it seems that they will stop providing dislikes in the youtube Data API.

Check #10 for that.

**Comment by null8626** [comment]
ah, i see. i hope to see a great future for your browser extension!

**Comment by pgamerx** [comment]
> ah, i see. i hope to see a great future for your browser extension!

Thanks!
