### ISSUE TITLE
Like/dislike bar is very tall

### ISSUE THREAD

**Issue by dben89x** [pgamerx/yt-dislikes-viewer#29]
The like/dislike bar stacks 6 of the following elements on top of each other, so that the bar comes out very tall:

    <div class="progress" id="test" style="position: relative; height: 3px; width: 40%; background: rgb(205, 205, 205);"><div class="color" id="color" style="position: absolute; background: rgb(6, 95, 212); width: 97.9588%; height: 3px;"></div></div>

![Screen Shot 2021-11-22 at 3 06 48 PM](https://user-images.githubusercontent.com/8463767/142942284-5b4722bc-83f0-4136-8cbe-e6f6ca8b047f.png)

Is this intended? When I manually remove 5 of the 6 elements, it seems to look right.

Below is a screenshot of the 6 stacked elements:

![Screen Shot 2021-11-22 at 3 01 02 PM](https://user-images.githubusercontent.com/8463767/142941666-002206d0-5e7f-4591-8310-d1c4ac9819cd.png)

And below is after removing 5 of the 6 elements:

![Screen Shot 2021-11-22 at 3 07 13 PM](https://user-images.githubusercontent.com/8463767/142942308-6ab5209b-70a4-41c1-b8cf-e8435af8491a.png)

**Comment by thereaper90917** [comment]
are you using the latest release here? that is a known bug from a previous release that got fixed :D

**Comment by pgamerx** [comment]
If I remember correctly, this was fixed in 1.6.6, but nonetheless I will check it.

**Comment by thereaper90917** [comment]
> If I remember correctly, this was fixed in 1.6.6, but nonetheless I will check it.

not sure the id in the screenshot is "test" we changed that to "custom-progress" when we did the fix for the ratio bar repeating itself. iirc

**Comment by dben89x** [comment]
> If I remember correctly, this was fixed in 1.6.6, but nonetheless I will check it.

This is bizarre. I have 1.6.6 installed on 3 devices. 

All devices are running Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)

On two of the three devices, the bar is short. On one of the devices, it's tall. The one device where it's tall is on a MacBook Air. The other two devices (MacBook Pro 15" and Mac Mini with a widescreen monitor) are fine.

I've double checked to make 100% sure that all devices are running the same version of Chromium and the same version of this repo. 

Is there anything I should test? I've tried different resolutions in the web inspector on all 3 devices, but nothing changes.

Edit: I'm actually seeing 3 elements stacked now on the MacBook Pro 15". It was just one bar when visiting youtube directly after installing the add-on. Tried a hard refresh, not sure what else I can try.

**Comment by Adib-C** [comment]
I can confirm that the bar is very tall on the 1.6.6 version

**Comment by Adib-C** [comment]
I think there is some conflict with PR #26 and #30 which caused this problem

**Comment by pgamerx** [comment]
> > If I remember correctly, this was fixed in 1.6.6, but nonetheless I will check it.
> 
> This is bizarre. I have 1.6.6 installed on 3 devices.
> 
> All devices are running Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
> 
> On two of the three devices, the bar is short. On one of the devices, it's tall. The one device where it's tall is on a MacBook Air. The other two devices (MacBook Pro 15" and Mac Mini with a widescreen monitor) are fine.
> 
> I've double checked to make 100% sure that all devices are running the same version of Chromium and the same version of this repo.
> 
> Is there anything I should test? I've tried different resolutions in the web inspector on all 3 devices, but nothing changes.
> 
> Edit: I'm actually seeing 3 elements stacked now on the MacBook Pro 15". It was just one bar when visiting youtube directly after installing the add-on. Tried a hard refresh, not sure what else I can try.

Today I will release v1.6.7, sorry for the issue and this shall be fixed in today's release (chromium only)

**Comment by hisRoyalty** [comment]
Is this issue fixed? If it is, it should be closed.

**Comment by pgamerx** [comment]
@dben89x it has been fixed in 1.7.5 aka latest release, sorry for the issue.
