### ISSUE TITLE
Put <!DOCTYPE html> on top of popup/index.html

### ISSUE THREAD

**Issue by ImNimboss** [pgamerx/yt-dislikes-viewer#3]
Every HTML5 file starts with `<!DOCTYPE html>` as its first line to indicate its HTML5, why doesn't `popup/index.html`?

**Comment by pgamerx** [comment]
Not necessary because it's just for the popup of extension

**Comment by ImNimboss** [comment]
Mmh the last time I forgot to put a doctype some of my document functions didn't work, if it works fine everywhere then leave it ig
