### ISSUE TITLE
API is difficult

### ISSUE THREAD

**Issue by WarriorDobby457** [pgamerx/yt-dislikes-viewer#43]
Is there another way to do some sort of verification?

**Comment by thereaper90917** [comment]
sadly no not currently but here's a video explaining it quite easy https://www.youtube.com/watch?v=N18czV5tj5o if you want a faster reply feel free to join the discord :) would gladly assist https://u.pgamerx.com/discord

**Comment by pgamerx** [comment]
> Is there another way to do some sort of verification?

This isn't for verification, if I would use my API key for all requests, it will never work because of the heavy usage. Moreover, using 1 api key for multiple users or using multiple API keys for 1 user is against Google's TOS.

**Comment by thereaper90917** [comment]
just an update our new versions will NOT require an API. it will be Optional.

**Comment by pgamerx** [comment]
Fixed in [1.8.3](https://github.com/pgamerx/yt-dislikes-viewer/releases/tag/v1.8.3)
