### ISSUE TITLE
mobile version of site

### ISSUE THREAD

**Issue by NotHuza** [pgamerx/yt-dislikes-viewer#44]
m.youtube.com
is host for mobile version youtube i use Firefox Nightly for android and i tested in android destop version of youtube and show dislike count i think this work perfect

watch?v=video id this is prefix for wach video

**Comment by thereaper90917** [comment]
would you mind joining the discord i might be able to make a few changes we could test :) https://u.pgamerx.com/discord if u are willing

**Comment by pgamerx** [comment]
Will be fixed in next version
