### ISSUE TITLE
UI is confusing

### ISSUE THREAD

**Issue by IMNdi** [pgamerx/yt-dislikes-viewer#45]
After installing the addon, it says "you need API key". Fine. I click the thing, get the API, paste it in, the key was red and clicking save makes it disappear. Ok, I guess it was wrong. I mean, it was red and nothing happened, that's the universal sign of a bad input.

Go back, redo the steps. Watch the video. Save the thing. Ok now what. I go look at OAUTH, define access, invite myself into the beta, make the thing work. All is green. WHAT.

After giving up, I went back to YT to watch a video and I noticed the dislikes worked now.

That is the worst feedback ever.

Suggestion, in order of difficulty:
- Check input to see if it looks like an API key. Make the text green if it looks like it's close by
- When saving the key, don't say "saved". Pop a dialog box that says "Key is saved, go to Youtube and refresh the page" or something.
- Ideally, when key is pasted, call an API and give feedback on whether the key is valid. "Key validated, refresh Youtube for results"

**Comment by pgamerx** [comment]
Thanks, will do the same in v1.8.1

**Comment by thereaper90917** [comment]
we removed the need to input an api so i don't think this would be needed anymore.

**Comment by pgamerx** [comment]
It is fixed in 1.8.3
