### ISSUE TITLE
Awkward gap between dislike bar and description

### ISSUE THREAD

**Issue by BlakkM9** [pgamerx/yt-dislikes-viewer#48]
There is a gap between the like/dislike and the thin line above the description which was not there on the original dislike bar. But that's a one line fix: just add
`progress.style.marginBottom = "-8px";`
where you set the style for the dislike bar (in script.js, around line 188).
i'd make a pull request but i'm honestly too lazy to do that for just a simple, single line, sorry!

**Comment by pgamerx** [comment]
We are currently working on API, we will fix this after API is back!
