### ISSUE TITLE
RE: Dislikes not loading

### ISSUE THREAD

**Issue by JBnirvana** [pgamerx/yt-dislikes-viewer#50]
Hey, I don't know if anyone else is having this issue, but the dislikes are no longer loading for me in version 1.8.3 for some reason. It was working great earlier today. Is it currently down or is this a bug, sorry my knowledge on the API's is very limited.

**Comment by pgamerx** [comment]
Hi there, yes the dislikes aren't visible anymore. We are working on fixing this and will be fixed temporarily within 24 hours. After that, we will make a permanent fix as well.

The main aim of our extension will shift from being just a "dislike viewer" to a "youtube customizer tool" which will still provide the functionality of viewing dislikes

**Comment by JBnirvana** [comment]
Awesome to hear, just wanted to make sure that I wasn't missing something. I very much appreciate the work that you're doing and wish you the best in your endeavors!

**Comment by pgamerx** [comment]
Thank you!
