### ISSUE TITLE
Uploading to the Chrome Web Store

### ISSUE THREAD

**Issue by psharma04** [pgamerx/yt-dislikes-viewer#8]
Hi, I saw your Reddit post about not being willing to pay to upload this to the Chrome web store, and was wondering if you'd like me to do it instead. I've filled out most of the process, and just need the following information to complete the upload:
Why does the extension need the following permissions?
  - tabs
  - notifications
  - scripting
  - webNavigation
  - storage
  - Host

Note: I'm already a verified developer with a paid account on the [Chrome web store.](https://chrome.google.com/webstore/detail/pulsarr/ekjjpacodipfmjhpbjcbnmnimakhlnne?hl=en)

**Comment by pgamerx** [comment]
Hi there, I would discourage doing this as I have already paid the fee with the help of some fellow redditors. 
Please do not continue the process because it will cause google to decline my request.
I hope you understand, Thanks

**Comment by pgamerx** [comment]
I have been trying for hours to get my dev account working and I finally got it working after so much time, Please understand
Thanks

**Comment by psharma04** [comment]
Okay, no problem! The only reason I was going it was in case you weren't planning on doing it, so thanks for clarifying :)

**Comment by pgamerx** [comment]
> Okay, no problem! The only reason I was going it was in case you weren't planning on doing it, so thanks for clarifying :)

Thank you, Thanks for understanding.
Have a great day
